version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - run:  
          name: Just let it pass
          command: |
            echo 'Hello world'
            pwd
            ls -la
            ls -la ~
            echo $SHELL
