version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
      environment:
        PGUSER: postgres
        PGHOST: 127.0.0.1
        NODE_ENV: test
      steps:
        - run: 
          name: Just let it pass
          command: |
            echo 'Hello world'
            pwd
            ls -la